let verbs, nouns, adjectives, adverbs, preposition

nouns = [
    'bird',
    'clock',
    'boy',
    'plastic',
    'duck',
    'teacher',
    'old lady',
    'professor',
    'hamster',
    'dog',
    'account',
    'middle',
    'act',
    'milk',
    'adjustment',
    'mind',
    'advertisement',
    'mine',
    'agreement',
    'minute',
    'air',
    'mist',
    'amount',
    'money',
    'amusement',
    'month',
    'animal',
    'morning',
    'answer',
    'mother',
    'apparatus',
    'motion',
    'approval',
    'mountain',
    'argument',
    'move',
    'attack',
    'name',
    'attempt',
    'nation',
    'attention',
    'need',
    'attraction',
    'news',
    'authority',
    'night',
    'back',
    'noise',
    'balance',
    'note',
    'base',
    'number',
    'behavior',
    'observation',
    'belief',
    'offer',
    'birth',
    'oil',
    'bit',
    'operation',
    'bite',
    'opinion',
    'breath',
    'pain',
    'brother',
    'paint',
    'building',
    'paper',
    'burn',
    'part',
    'burst',
    'paste',
    'business',
    'payment',
    'butter',
    'peace',
    'canvas',
    'person',
    'care',
    'place',
    'cause',
    'plant',
    'chalk',
    'play',
    'chance',
    'pleasure',
    'change',
    'point',
    'force',
    'song',
    'form',
    'sort',
    'friend',
    'sound',
    'front',
    'soup',
    'fruit',
    'space',
    'glass',
    'stage',
]

verbs = [
    'be',
    'have',
    'do',
    'say',
    'go',
    'can',
    'get',
    'would',
    'make',
    'know',
    'will',
    'think',
    'take',
    'see',
    'come',
    'could',
    'want',
    'look',
    'use',
    'find',
    'give',
    'tell',
    'work',
    'may',
    'should',
    'call',
    'try',
    'ask',
    'need',
    'feel',
    'become',
    'leave',
    'put',
    'mean',
    'keep',
    'let',
    'begin',
    'seem',
    'help',
    'talk',
    'turn',
    'start',
    'might',
    'show',
    'hear',
    'play',
    'run',
    'move',
    'like',
    'live',
    'believe',
    'hold',
    'bring',
    'happen',
    'must',
    'write',
    'provide',
    'sit',
    'stand',
    'lose',
    'pay',
    'meet',
    'include',
    'continue',
    'set',
    'learn',
    'change',
    'lead',
    'understand',
    'watch',
    'follow',
    'stop',
    'create',
    'speak',
    'read',
    'allow',
    'add',
    'spend',
    'grow',
    'open',
    'walk',
    'win',
    'offer',
    'remember',
    'love',
    'consider',
    'appear',
    'buy',
    'wait',
    'serve',
    'die',
    'send',
    'expect',
    'build',
    'stay',
    'fall',
    'cut',
    'reach',
    'kill',
    'remain',
]

adjectives = [
    'accurate',
    'agreeable',
    'affectionate',
    'ambitious',
    'approachable',
    'articulate',
    'artistic',
    'attractive',
    'brave',
    'calm',
    'cautious',
    'careful',
    'charming',
    'cheerful',
    'clean',
    'comfortable',
    'confident',
    'clever',
    'cool',
    'competent',
    'considerate',
    'contented',
    'cultured',
    'decisive',
    'dependable',
    'dynamic',
    'direct',
    'discreet',
    'discontented',
    'delightful',
    'detailed',
    'dedicated',
    'determined',
    'dazzling',
    'easy-going',
    'efficient',
    'enthusiastic',
    'excitable',
    'faithful',
    'fair',
    'flexible',
    'friendly',
    'fun',
    'funny',
    'generous',
    'gentle',
    'great',
    'generous',
    'hard-working',
    'happy',
    'helpful',
    'honest',
    'humorous',
    'imaginative',
    'intelligent',
    'interesting',
    'kind',
    'likable',
    'logical',
    'loveable',
    'loving',
    'loyal',
    'mature',
    'modest',
    'obedient',
    'open-minded',
    'optimistic',
    'organized',
    'passionate',
    'patient',
    'pleasant',
    'polite',
    'positive',
    'powerful',
    'practical',
    'quiet',
    'romantic',
    'relaxed',
    'reserved',
    'respectful',
    'responsive',
    'rational',
    'realistic',
    'reasonable',
    'relaxed',
    'reliable',
    'resourceful',
    'sane',
    'sensible',
    'sensitive',
    'sincere',
    'smart',
    'sociable',
    'strong',
    'tactful',
    'thoughtful',
    'trustworthy',
    'unique',
    'willing',
    'youthful'
]

adverbs = [
    'accidentally',
    'always',
    'angrily',
    'arrogantly',
    'badly',
    'beautifully',
    'bitterly',
    'blindly',
    'boldly',
    'bravely',
    'briefly',
    'busily',
    'boastfully',
    'boldly',
    'bashfully',
    'brightly',
    'carefully',
    'certainly',
    'clearly',
    'courageously',
    'cruelly',
    'curiously',
    'commonly',
    'calmly',
    'carelessly',
    'cautiously',
    'cheerfully',
    'cleverly',
    'closely',
    'coaxingly',
    'colorfully',
    'continually',
    'correctly',
    'crossly',
    'daily',
    'delightfully',
    'easily',
    'enthusiastically',
    'eventually',
    'exactly',
    'excitedly',
    'extremely',
    'fairly',
    'faithfully',
    'fast',
    'foolishly',
    'fortunately',
    'frankly',
    'generally',
    'generously',
    'gently',
    'gracefully',
    'gladly',
    'gleefully',
    'gratefully',
    'greatly',
    'greedily',
    'happily',
    'highly',
    'honestly',
    'hopelessly',
    'immediately',
    'innocently',
    'instantly',
    'interestingly',
    'jealously',
    'joyfully',
    'kindly',
    'keenly',
    'kiddingly',
    'kindheartedly',
    'kookily',
    'knowingly',
    'knavishly',
    'lively',
    'lazily',
    'less',
    'loudly',
    'lovingly',
    'loyally',
    'loosely',
    'madly',
    'more',
    'mysteriously',
    'naturally',
    'nearly',
    'nervously',
    'never',
    'obediently',
    'officially',
    'often',
    'openly',
    'painfully',
    'patiently',
    'politely',
    'poorly',
    'positively',
    'properly',
    'quickly',
    'quietly'
]

preposition = [
    'about',
    'above',
    'across',
    'after',
    'against',
    'among',
    'around',
    'at',
    'before',
    'behind',
    'below',
    'beside',
    'between',
    'by',
    'down',
    'during',
    'for',
    'from',
    'in',
    'inside',
    'into',
    'near',
    'of',
    'off',
    'on',
    'out',
    'over',
    'through',
    'to',
    'toward',
    'under',
    'up',
    'with',
    'aboard',
    'along',
    'amid',
    'as',
    'beneath',
    'beyond',
    'but',
    'concerning',
    'considering',
    'despite',
    'except',
    'following',
    'like',
    'minus',
    'next',
    'onto',
    'opposite',
    'outside',
    'past',
    'per',
    'plus',
    'regarding',
    'round',
    'save',
    'since',
    'than',
    'till',
    'underneath',
    'unlike',
    'until',
    'upon',
    'versus',
    'via',
    'within',
    'without',
    'ask out',
    'back up',
    'break up',
    'break in',
    'call off',
    'call on',
    'check in',
    'dress up',
    'drop in',
    'drop off',
    'fall down',
    'fill in',
    'fill out',
    'find out',
    'get around',
    'give away',
    'give in',
    'hand out',
    'hang up',
    'keep up',
    'make up',
    'put down',
    'set up',
    'show off',
    'take back',
    'take off',
    'turn down',
    'try out',
    'work out',
    'because of',
    'as a result of',
    'is due to'
]


export const makeSentence = (quoteLength) => {
    let para = [];

    while(para.length<quoteLength){
        let rand = Math.floor(Math.random() * 100)
        para.push(nouns[rand]);
        if(para.length >= quoteLength) break;
        
        para.push(verbs[rand]);
        if(para.length >= quoteLength) break;

        para.push(adjectives[rand]) 
        if(para.length >= quoteLength) break;

        para.push(adverbs[rand])
        if(para.length >= quoteLength) break;

        para.push(preposition[rand])
        if(para.length >= quoteLength) break;
    }
    return para.join(' ');
}